### ISSUE TITLE
Error when trying to launch mod (1.19.2 Quilt)

### ISSUE THREAD

**Issue by Steveplays28** [agnor99/passive-chunk-pregenerator#2]
```bash
Oct 20, 2022 1:00:15 AM org.prismlauncher.EntryPoint listen
 SEVERE: Exception caught from launcher. 

java.lang.reflect.InvocationTargetException 
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) 
  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
  at java.base/java.lang.reflect.Method.invoke(Method.java:568) 
  at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) 
  at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) 
  at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186) 
  at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144) 
  at org.prismlauncher.EntryPoint.main(EntryPoint.java:74)
 Caused by: java.lang.RuntimeException: Failed to read accessWidener file from mod passivepregen 
at org.quiltmc.loader.impl.QuiltLoaderImpl.loadAccessWideners(QuiltLoaderImpl.java:585) 
at org.quiltmc.loader.impl.launch.knot.Knot.init(Knot.java:144) 
at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:70) 
at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:24) 
... 9 more 
Caused by: net.fabricmc.accesswidener.AccessWidenerFormatException: line 1: Namespace (named) does not match current runtime namespace (intermediary) 
at net.fabricmc.accesswidener.AccessWidenerReader.error(AccessWidenerReader.java:285) 
at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:84) 
at org.quiltmc.loader.impl.QuiltLoaderImpl.loadAccessWideners(QuiltLoaderImpl.java:583) 
... 12 more 

Oct 20, 2022 1:00:16 AM org.prismlauncher.EntryPoint main 
INFO: Exiting with 1 
Process exited with code 1.
```

I'm using PrismLauncher, for reference. This is on 1.19.2 Quilt, with a bunch of other mods.

Also, the mod version is incorrectly displayed. It's displayed as `${version}`, instead of an actual version number.  
Not sure if this is fixed already, I can make a new issue for this if you want.

**Comment by TechPro424** [comment]
I have the same issue, but on Fabric 1.19.2: https://mclo.gs/zksWTz2

**Comment by ghost** [comment]
Same issue for me on 1.19.2 Quilt.

Though I'm not sure my logs reveal any further information, here it is anyway:  
[latest.log](https://github.com/agnor99/passive-chunk-pregenerator/files/9843262/latest.log)

**Comment by TechPro424** [comment]
I think I found the error
When you build the mod, it generates 2 jar files
one with `-sources` in the name, and one without it
The one on modrinth has `-sources`
But whenever you distribute a mod for people to use, you're apparently supposed to distribute only the one without `-sources`

**Comment by TechPro424** [comment]
@agnor99 please fix this, its been an entire month now

**Comment by justliliandev** [comment]
correct file should be uploaded to modrinth now

**Comment by Steveplays28** [comment]
Thank you!

**Comment by TechPro424** [comment]
Thanks a lot!
